### ISSUE TITLE
Unable to call mg-api-js module from Node.Js app

### ISSUE THREAD

**Issue by vsharan** [Geotab/mg-api-js#3]
Hi Team,

We tried to integrate the module in our Node.Js application. But it is using `dist/api.min.js` which was missing in `mg-api-js` module when we installed it.

Is there any way if we could directly use `api.js` instead of `api.min.js` ? Since the file `api.min.js` does not exists in dist directory.

Error
`Error: Cannot find module 'F:\development\projects\geoTab\my-demo\node_modules\mg-api-js\dist\api.min.js'. Please verify that the package.json has a valid "main" entry`

**Comment by beefo** [comment]
Ya, I think it's better to have `dist/api.min.js` and `dist/api.js`.

**Comment by vsharan** [comment]
Can you please do it. Since I am using it in Node.Js and there is no `min `file by default when we install the module `mg-api-js`

**Comment by beefo** [comment]
@vsharan we pushed v2.0.1, just let us know if there's any other issues.

**Comment by vsharan** [comment]
@beefo Thank you for the support. I will try again and let you know.

**Comment by Hedronmx** [comment]
I am having problems using the node module as well, i get the following error 

```
This dependency was not found:

* module in ./node_modules/mg-api-js/dist/api.min.js
```

I have installed the module numerous time and the file is there but I cant get the dependency to show up
