### ISSUE TITLE
Confusing error message given when using improperly formed authentication object

### ISSUE THREAD

**Issue by pjroth** [Geotab/mg-api-js#7]
I am using the API in a nodeJS application running via AWS Lambda.  The lambda invocations return successfully for a time and then at some point start to return the following error:
```
ERROR	Error: JSONRPCError - Object reference not set to an instance of an object.
    at eval (webpack://%5Bname%5D/./src/geotab-api-layer/node_modules/mg-api-js/dist/api.min.js?:5:37744)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'm using version `2.0.1` of `mg-api-js`

**Comment by pjroth** [comment]
This problem seems to be intermittent.  If I wait some amount of time things will start working again.

**Comment by pjroth** [comment]
Steps to reproduce:

1. Code is setup to create GeotabApi using `sessionId` authentication with `fullResponse` option left as default value of `false`
1. Use this API to do a GET on `Device`
1. Invoke my code multiple times, sometimes with all valid authentication `credentials` object (Geotab API succeeds) and sometimes with required fields null in the `credentials` object (e.g. `credentials.database is null` which causes the request to fail.
1. Keep invoking the code over and over until eventually the case where even when a valid `credentials` object is used in the `Authenticate` request it fails with the `Object reference not set` error above.

I'm doing this in an AWS lambda function behind an API Gateway in case that matters using NodeJS version 12.

I wait awhile and invoke the code again, it will eventually start to succeed again (when valid `credentials` object is used).

**Comment by pjroth** [comment]
Looking at the minified code I think the error is on this line:  https://github.com/Geotab/mg-api-js/blob/5ba6b434563badaee28396ebf0f0f82bec0b8d8c/lib/ApiHelper.js#L154

**Comment by pjroth** [comment]
I updated my code to make the `Authenticate` request with the option of `fullResponse = true` and now I get this error:

```
ERROR	Error: JSONRPCError - Incorrect login credentials
    at eval (webpack://%5Bname%5D/./src/geotab-api-layer/node_modules/mg-api-js/dist/api.min.js?:5:37744)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by beefo** [comment]
@pjroth These look to be error responses from the server. 

> Invoke my code multiple times, sometimes with all valid headers (Geotab API succeeds) and sometimes with a missing geotab-database header which causes the request to fail.

What do you mean by missing database header? Can you provide an example?

**Comment by pjroth** [comment]
@beefo sorry that was info about my application.  Those headers are converted into properties on the `credentials` object passed to Geotab api in the `Authenticate` request.  If the header is not present then that property in the `credentials` object is null.

I updated my steps to reproduce above to remove terminology from my application and only use terms from this project.

**Comment by pjroth** [comment]
I've narrowed down the steps to reproduce.  It seems that me making the requests with the `credentials` object with nulls is what causes this to start failing.  If I am passing a correct/populated `credentials` object I can submit many requests without failing.  If I make a few requests without a valid `credentials` object these fail as expected.  I then start making valid requests again and the valid requests fail with the `Object reference not set` error.

**Comment by beefo** [comment]
@pjroth let me parrot back to you the repro steps so I'm clear I understand
1. authenticate to get valid credentials object
2. make requests with valid, populated properties of credentials (userName, database, sessionId)
3. make requests with _unpopulated_ properties of credentials
4. make requests with valid, populated properties of credentials

At step 4 the null ref occurs and is non-recoverable?

This is all using the same instance of an API object?

**Comment by pjroth** [comment]
> At step 4 the null ref occurs and is non-recoverable?

Correct.  If I make more invocations to my lambda they all seem to fail at 4.  Unless I wait "awhile" (10m or more perhaps, exact time I'm not sure).  After I wait, then things work again.

>This is all using the same instance of an API object?

No, I'm running in AWS Lambda.  Each lambda invocation creates a new Geotab api instance, authenticates, and then makes the Geotab request to something like `Devices`, then the invocation ends.  The next invocation does that all over again.  There is no shared state between invocations.

**Comment by beefo** [comment]
CC @NolanKingdon

**Comment by NolanKingdon** [comment]
@pjroth Are you using a `const` for your `credentials` object? I was able to reproduce by declaring my `credentials` as a `const`, and sharing that `const` across multiple functions.

The cause for me when I replicated was that `const` creates a reference to the `credentials` object in memory. To create a failing call, I was changing the `credentials` object in my invalid calls to have null parameters when creating the new `GeotabApi` object. When I went to re-use the `credentials` object to create another Api instance it still had the null values because the `credentials` object being referenced in each function was the same object in memory, causing my valid attempt to fail.

If the invalid and valid calls happen close enough together, AWS Lambda may be doing a '[Warm Start](https://dev.to/sosnowski/anatomy-of-aws-lambda-1i1e#warm-start)' of the service which might be carrying the mutated `credentials` object over to your next Lambda event. Waiting for 10 or so minutes could be resulting in a 'Cold Start', which would also reset the `const credentials` object and let requests succeed again.

**Comment by pjroth** [comment]
Yes we are using a `const` for our `credentials` object.  I'm guessing the Warm Start vs Cold Start and my use of a `const` to store this as you described is what is going on.  I was surprised to learn that those `const`s are being reused like that from one lambda invocation to the next on the same "instance".  I need to fix my code to not do that now that I understand how lambda executes things which should avoid the original Exception I'm getting.

Ok, so maybe the issue here is just that if you use nulls you get an Exception that is very hard to decipher as to what the problem really is.  I'd prefer to see an exception immediately when I tried to use arguments (nulls) that are invalid.  Certainly I understand this is probably lower priority.  But it would have helped speed up debugging in my case I think.

Thanks for all the help @NolanKingdon !

**Comment by pjroth** [comment]
Were any error message improvements or other changes made?
